name: Validate Commit Messages (Python)

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  validate-commits:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install GitHub CLI
        uses: cli/gh-action@v2

      - name: Install dependencies
        run: pip install --quiet requests

      - name: Run commit message validator
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          python .github/scripts/validate_commit_messages.py ${{ github.event.pull_request.number }}
